language: node_js
dist: xenial
node_js: lts/*
sudo: true

before_script:
  - yarn add global http-server
  - http-server &
  - webpack

script:
  - yarn test

after_failure:
  - zip -r diff_output.zip test/__image_snapshots__/__diff_output__
  - curl -F'file=@diff_output.zip' http://0x0.st

notifications:
  email:
    on_success: never
