language: node_js
dist: trusty
node_js: 8.11
sudo: required

before_script:
  - yarn add global http-server
  - http-server &
  - webpack

script:
  - yarn test

notifications:
  email:
    on_success: never
